# Change 'comments' to true for Disqus comments
disqus:
  comments: true
  disqus_shortname: 'https-yhaddad-github-io'

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: 'UA-98286067-1'

menu:
- {name: 'About'    , path: 'menu', url: 'about.html'}  
- {name: 'Writtings', path: 'blog', url: 'index.html'}
- {name: 'Talks'    , path: 'menu', url: 'talks.html'}
- {name: 'Publications', path: 'menu', url: 'publications.html'}
- {name: 'Contact'  , path: 'menu', url: 'contact.html'}
#- {name: 'Archive', path: 'menu', url: 'writing.html'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'github'    , link: 'https://www.github.com/yhaddad'}
- {icon: 'twitter'   , link: 'https://twitter.com/DrYacineHaddad'}
- {icon: 'linkedin'  , link: 'https://uk.linkedin.com/in/yacine-haddad'}
- {icon: 'envelope'  , link: 'mailto:haddad.yacine.phys@gmail.com'}
- {icon: 'rss-square', link: '/rss-feed.xml'}
  #- {icon: 'keybase'   , link: 'https://keybase.io/yfalcon'}

# Customize site text
pagination:
  next_page: 'Next'
  previous_page: 'Older'

sharing_button_prompt: 'Feel free to share!'

related_posts: 'You may also enjoy:'

post_date_prefix: 'Written on'
